version: "3.8"
name: car-rental-website
services:
  php:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ../:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3307:3306
    volumes:
      - ../SQL:/SQL/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

  composer:
    restart: "no"
    image: composer:latest
    volumes:
      - ../:/var/www/html/
    working_dir: /var/www/html
    command: ["composer", "install"]
